"""
Report Writer agent — Phase 4.

Responsibilities:
  - Render Jinja2 template with signals from state["signals"]
  - NO LLM involved — pure deterministic template rendering
  - Validate ReportModel (disclaimer_present is a required Pydantic field)
  - Write report_md to state["report_md"]
  - Persist report to SQLite

Template: templates/report.md.j2

Phase 0: stub implementation.
"""

from __future__ import annotations

import logging
from typing import Any

from src.state import AgentState
from src.tracing import trace

logger = logging.getLogger(__name__)

TEMPLATE_NAME = "report.md.j2"
LEGAL_DISCLAIMER = (
    "DISCLAIMER: This report is generated by an automated AI system for "
    "informational purposes only. It does not constitute financial advice, "
    "investment recommendations, or solicitation to buy or sell securities. "
    "Always conduct your own due diligence. Past signal accuracy does not "
    "guarantee future results."
)


@trace(name="report_writer", tags=["phase-4", "report"])
def report_writer_node(state: AgentState) -> dict[str, Any]:
    """
    STUB — Phase 4 implementation pending (Session 5).

    Will:
      1. Load Jinja2 template from templates/report.md.j2.
      2. Render with state["signals"] and run metadata.
      3. Assert disclaimer is present in rendered output.
      4. Validate ReportModel (disclaimer_present=True required).
      5. Return {"report_md": rendered_markdown_string}.

    Note: This node must NEVER call Claude or any LLM. Report formatting
    is deterministic — only template variable substitution.
    """
    logger.info(
        "report_writer: STUB — skipping report render (Phase 4 not yet implemented)"
    )
    return {"report_md": ""}


@trace(name="memory_agent", tags=["phase-4", "memory"])
def memory_agent_node(state: AgentState) -> dict[str, Any]:
    """
    Memory / persistence agent — Phase 4.

    STUB — Phase 4 implementation pending (Session 5).

    Will:
      1. Persist each SignalModel in state["signals"] to SQLite.
      2. Persist run metadata to SQLite runs table.
      3. Compute novelty scores by comparing current signals to
         previous run in SQLite (feeds back into signal_synthesis in Phase 3).
      4. Return {} (no state mutations — side effects only).
    """
    logger.info(
        "memory_agent: STUB — skipping SQLite persistence (Phase 4 not yet implemented)"
    )
    return {}
